namespace TastyTradeApi.Core.Accounts;
public record TradingStatusResponse(
    string AccountNumber,
    string EquitiesMarginCalculationType,
    string FeeScheduleName,
    string FuturesMarginRateMultiplier,
    bool HasIntradayEquitiesMargin,
    int Id,
    bool IsAggregatedAtClearing,
    bool IsClosed,
    bool IsClosingOnly,
    bool IsCryptocurrencyClosingOnly,
    bool IsCryptocurrencyEnabled,
    bool IsFrozen,
    bool IsFullEquityMarginRequired,
    bool IsFuturesClosingOnly,
    bool IsFuturesIntraDayEnabled,
    bool IsFuturesEnabled,
    bool IsInDayTradeEquityMaintenanceCall,
    bool IsInMarginCall,
    bool IsPatternDayTrader,
    bool IsPortfolioMarginEnabled,
    bool IsRiskReducingOnly,
    bool IsSmallNotionalFuturesIntraDayEnabled,
    bool IsRollTheDayForwardEnabled,
    bool AreFarOtmNetOptionsRestricted,
    string OptionsLevel,
    bool ShortCallsEnabled,
    string SmallNotionalFuturesMarginRateMultiplier,
    bool IsEquityOfferingEnabled,
    bool IsEquityOfferingClosingOnly,
    DateTime EnhancedFraudSafeguardsEnabledAt,
    DateTime UpdatedAt);


